### PR TITLE
Migrate pmem deprecated API to the new one

### PR DESCRIPTION
**Pull request by mickybart**
This patch permit to migrate deprecated functions pmem_kalloc and pmem_kfree to the new API.

Migration is done for : 
tzcom
qdsp6
msm/vidc

This patch revert the emulation of deprecated pmem_kalloc and pmem_kfree on the memory.c and android_pmem.h files.

ZRAM support : patch zram to run on arm architecture + enable on defconfig

### CODE REVIEW

**Comment by mickybart** [comment]
Billchen1977,

I'm not sure but it seems that the pull request include this patch "clock-8x60: add jpegd_clk for msm_mercury".
I have created and validate this patch after the creation of this pull request. I have created another pull request for clock-8x60.

Just check because maybe the second pull request is not necessary. Maybe a mistake on my side or maybe this is a normal github behaviour. Not sure about that.

Thanks

**Comment by mickybart** [comment]
Patches for zram/swap support if you want it

**Comment by billchen1977** [comment]
Some busy these days, sorry for my late reply.
pmem old api patch seem actual the same thing, and affect too many files , so I just ingore it,sorry.
zram patch will merge manual when I have time, thank a lot.

**Comment by mickybart** [comment]
No problem billchen1977, I'm busy too. If you want I can provide a patch with zram only and remove the patch for deprecated pmem API ?
Do you want me to provide the zram implementation into device_sony_nozomi too or do you prefer to implement it directly on the fstab as defined by Google in the implementation ?
Let me know and I will do that.

**Comment by billchen1977** [comment]
I have manual merge it today, thank you.
I mix fstab init script. you see detail in the commit.

**Comment by mickybart** [comment]
I just saw that :)
Thanks I will align myself with your implementation to have an easy maintenance.
I close the pull request :)

**Pull request closed without merging**
